config/routes.rb
KVmaker::Application.routes.draw do
  resources :kvs

  root :to => 'kvs#index'

end

app/models/kv.rb
class Kv < ActiveRecord::Base
  attr_accessible :fields, :values, :input
  validates :fields, :values, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/kvs_controller.rb
class KvsController < ApplicationController
  # GET /kvs
  # GET /kvs.json
  def index
    @kvs = Kv.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kvs }
    end
  end

  # GET /kvs/1
  # GET /kvs/1.json
  def show
    @kv = Kv.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kv }
    end
  end

  # GET /kvs/new
  # GET /kvs/new.json
  def new
    @kv = Kv.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kv }
    end
  end

  # GET /kvs/1/edit
  def edit
    @kv = Kv.find(params[:id])
  end

  # POST /kvs
  # POST /kvs.json
  def create
    @kv = Kv.new(params[:kv])

    respond_to do |format|
      if @kv.save
        format.html { redirect_to @kv, notice: 'Kv was successfully created.' }
        format.json { render json: @kv, status: :created, location: @kv }
      else
        format.html { render action: "new" }
        format.json { render json: @kv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kvs/1
  # PUT /kvs/1.json
  def update
    @kv = Kv.find(params[:id])

    respond_to do |format|
      if @kv.update_attributes(params[:kv])
        format.html { redirect_to @kv, notice: 'Kv was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kvs/1
  # DELETE /kvs/1.json
  def destroy
    @kv = Kv.find(params[:id])
    @kv.destroy

    respond_to do |format|
      format.html { redirect_to kvs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kvs_helper.rb
module KvsHelper
  def calculate_latex_normal_form(kv)
    str = ''
    str += add_lines(kv.fields.split(", "), kv.values.split(", ")).chomp(' &+ ')
    logger.debug "the sting is: #{str}"
    logger.debug "the fields were #{kv.fields.split(', ')}"
    logger.debug "the input was #{kv.values.split(', ')}"
    return str
  end

  def add_lines(fieldnames, data)
    str = ''
    data.each do |line|
      str += '( '
      i = 0
      values = line.split(" ")
      values.each do |value|
        str += add_value(fieldnames, value, i)
        i += 1
      end
      str = str.chomp(' * ')
      str += ' ) \\\\
      &+ '
    end
    return str
  end

  def add_value(fieldnames, value, i)
    get_output(fieldnames, value, i) + ' * '
  end

  def calculate_latex_table(kv)
    str = print_diagram_header(kv.fields.split(", "), kv.input)
    str += print_each_combination(kv.input)
    str += print_diagram_footer
    return str
  end

  def print_diagram_header(fields, input)
    input_values = ''
    input.times{ input_values += 'c'}
    input_values += '|'
    (fields.length - input).times{ input_values += 'c' }
    str = "\\begin{center}
    \\begin{tabular}{#{input_values}}
    $"
    str += fields.split(",").join("$ & $")
    str += '$\\\\
     '

    return str
  end

  def print_each_combination(width)
    str = ''
    i = 0
    while (i < 2 ** width)
      value = i.to_s(2)
      value = add_zeros(value, width) if value.length < width
      str += value.split('').join(' & ')
      str += ' \\\\
      '
      i += 1
    end
    return str
  end

  def add_zeros(value, width)
    out = value
    while (out.length < width) do
      out = "0" + out
    end
    return out
  end

  def print_diagram_line(fields, values)
    i = 0
    str = ''
    values.split(" ").each do |x|
      logger.debug "line #{i} => #{x}"
      str += "#{get_output(fields, x, i)} & "
      i += 1
    end
    return str.chomp(" &") + " \\\\"
  end


  def print_diagram_footer
    return '\end{tabular}
            \end{center}'
  end

  def get_output(fields, value, i)
    if value == '1'
      "#{fields[i]}"
    else
      "\\overline{#{fields[i]}}"
    end
  end

  def generate_KV_diagrams(kv)
    str = ''
    (kv.fields.split(", ").length - kv.input).times{|x| str += generate_KV_diagram(kv, x)}
    return str
  end

  def generate_KV_diagram(kv, number)
    str = "\\input kvmacros
    \\karnaughmap{#{kv.input}}{$#{generate_KV_function(kv, number)}:$}{#{generate_KV_inputs(kv)}}{#{generate_KV_values(kv)}}
    {

    }
    "
  end

  def generate_KV_function(kv, number)
    str = "#{kv.fields.split(", ")[(kv.input + number)]}( "
    str += kv.fields.split(", ")[0..(kv.input - 1)].join(", ")
    str.chomp(", ")
    return str + ")"
  end

  def generate_KV_inputs(kv)
    str = ''
    kv.fields.split(", ")[0..(kv.input - 1)].each{|x| str += "{$#{x}$}"}
    return str
  end

  def generate_KV_values(kv)
    str = ''
    (2 ** kv.input).times{|x| str += '0'}
    return str.gsub(/\s+/, "")
  end
end

app/views/kvs/_form.html.erb
<%= form_for(@kv) do |f| %>
  <% if @kv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kv.errors.count, "error") %> prohibited this kv from being saved:</h2>

      <ul>
      <% @kv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Seperate value names by comma</strong>
    <%= f.label :fields %><br />
    <%= f.text_field :fields %>
  </div>
  <div class="field">
    <strong>How many fields are inputs?</strong>
    <%= f.label :input %><br />
    <%= f.text_field :input %>
  </div>
  <div class="field">
    Add all the ones!
    <strong>Seperate single value names by space, lines by comma</strong>
    <%= f.label :values %><br />
    <%= f.text_field :values %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kvs/_kv.html.erb
<%= div_for kv do %>
<table>
  <tr>
    <td><%= kv.fields %></td>
    <td><%= kv.input %></td>
    <td><%= kv.values %></td>
    <td>
      <textarea cols="40" rows="10" id="post_body" name="post[body]">
        Wertetabelle:
        <%= calculate_latex_table(kv) %>
        Normalform:
        <%= calculate_latex_normal_form(kv) %>
        KV Diagramme:
        <%= generate_KV_diagrams(kv) %>
      </textarea>
    </td>
    <td><%= link_to 'Show', kv %></td>
    <td><%= link_to 'Edit', edit_kv_path(kv) %></td>
    <td><%= link_to 'Destroy', kv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</table>
<% end %>

app/views/kvs/edit.html.erb
<h1>Editing kv</h1>

<%= render 'form' %>

<%= link_to 'Show', @kv %> |
<%= link_to 'Back', kvs_path %>

app/views/kvs/index.html.erb
<h1>Listing kvs</h1>

<table>
  <tr>
    <th>Fields</th>
    <th>Values</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render @kvs %>
</table>

<br />

<%= link_to 'New Kv', new_kv_path %>

app/views/kvs/new.html.erb
<h1>New kv</h1>

<%= render 'form' %>

<%= link_to 'Back', kvs_path %>

app/views/kvs/show.html.erb
<p id="notice"><%= notice %></p>
<%= render @kv %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KVmaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>